### ISSUE TITLE
wrong node engine

### ISSUE THREAD

**Issue by kylebakerio** [Vesper0704/naf-mediasoup-adapter#1]
https://github.com/Vesper0704/naf-mediasoup-adapter/blob/68b70d3f19b35d99b465959080312f8788486027/package.json#L58

This should be at least node 14, because you use the conditional chaining operator, which wasn't supported in node until v14. Probably ideal to use v16, though, as that's the current LTS if I'm not mistaken?

**Comment by Vesper0704** [comment]
Yeah. I forgot to make this right before I upload. And the LTS for node is 18.12.1 by now.

**Comment by vincentfretin** [comment]
It seems you have addressed it in https://github.com/Vesper0704/naf-mediasoup-adapter/commit/526af46cd0933f350df63b4b5b3abbc3f7d483d8 so you can close.
